spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: api-gateway-i1

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
