spring:
  cloud:
    consul:
      # host: localhost
      # port: 8500
      discovery:
        instance-id: api-gateway-i1
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : books-app-route
          uri: lb://books-app
          predicates:
            - Path=/books-app/api/v0.1/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: bookCircuitBreakers
                fallbackUri: forward:/fallback/appFallback

        - id: authentication-users-route
          uri: lb://authentication-users    
          predicates:
            - Path=/authentication-users/auth/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreakers

        - id: wf-route
          # uri: lb://working-files  
          uri: lb://working-file-svc
          predicates:
            # - Path=/working-files/api/v0.1/**
            - Path=/working-file-svc/api/v0.1/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: wfCircuitBreakers
                fallbackUri: forward:/fallback/appFallback


management:
  health:
    circuitbreakers:
       enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 2
          
