spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/InternshipITexus
    username: postgres
    password: pgadmin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  cloud:
    consul:
      discovery:
        instance-id: authentication-users-i1


server:
  port: 0
