spring:
 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/InternshipITexus
   username: postgres
   password: pgadmin
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       show_sql: true
       cache:
         use_query_cache: true
         use_second_level_cache: true
         region:
           factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
 cloud:
   consul:
     discovery:
       instance-id: books-app-i1

