spring:
  kafka:
    bootstrap-servers: kafka-svc:9092
    consumer:
      group-id: consumer-group  
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    consul:
      discovery:
        instance-id: kafka-consumer-i1
    
