spring:
  data:
    mongodb:
      # host: localhost
      # port: 27017
      # database: icons

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  cloud:
    consul:
      discovery:
        instance-id: working-files-i1
